### ISSUE TITLE
Error in executing the svafotate_main python script

### ISSUE THREAD

**Issue by priyambial123** [fakedrtom/SVAFotate#17]
Hello,

I have been running svafotate analysis without any error. Now, I get an error when I run the svafotate script. Please find the below script used. I tried to change chrom to CHROM in the script as the header in the vcf has CHROM or other way around in the vcf. But, it didn't work

Thank you

```
svafotate annotate -v "/pbsv/23.GRCh38.pbsv.vcf.gz" -o "/pbsv/23.GRCh38.pbsv.svafotate.vcf" -b "/pbsv/SVAFotate_core_SV_popAFs.GRCh38.bed.gz"  -b "pbsv/TOPMed.GRCh38.bed.gz"  -f 0.5 -a EUR -u 0

Annotating the following VCF: /pbsv/23.GRCh38.pbsv.vcf.gz

Reading the following data source file: /pbsv/TOPMed.GRCh38.bed.gz

Annotating with the following sources and reciprocal overlap fractions:
TOPMed  0.5

Additional annotations requested:
EUR population frequencies and counts

Producing uniques.bed output and SV_Uniq annotation requested; AF cutoff of: 0.0

Gathering SV coordinates from VCF file: /pbsv/23.GRCh38.pbsv.vcf.gz

Creating pyranges object from VCF data...

Running pyranges.join for:
TOPMed

Creating pyranges objects per SVTYPE from VCF data...

Running pyranges.subtract for:
BND
Traceback (most recent call last):
  File "/mambaforge/envs/svafotate-env/bin/svafotate", line 8, in <module>
    sys.exit(main())
  File "/mambaforge/envs/svafotate-env/lib/python3.8/site-packages/svafotate/__main__.py", line 41, in main
    args.func(parser, args)
  File "/mambaforge/envs/svafotate-env/lib/python3.8/site-packages/svafotate/svafotate_main.py", line 996, in annotate
    pr_bed = pr.from_dict({"Chromosome": fin_uniq_lists['chrom'], \
KeyError: 'chrom'

```

**Comment by fakedrtom** [comment]
Thank you for bringing this to my attention. This error appears to be coming from the extra functions that are being used because of the inclusion of the `-u` parameter, but only with the `TOPMed.GRCh38.bed.gz` BED file (similarly, this happens with the `-c` parameter as well). I am looking into why this is, but for the time being, if you omit the `-u` parameter, I think it should run without error for you. I'll work on resolving this and hopefully have a fix so the `-u` parameter can be used with `TOPMed.GRCh38.bed.gz` soon enough. 

By the way, in the command above you have included the required `-b` parameter twice. This is defaulting to whichever BED you supplied last (the second `-b`), in this case the `TOPMed.GRCh38.bed.gz` one. Only one BED is used.

**Comment by fakedrtom** [comment]
Ok, I believe I have pushed a fix that should work. Give it and try and let me know if you still see the error. Thanks!
