### ISSUE TITLE
Invalid tag name: "1000G_Count"

### ISSUE THREAD

**Issue by prasundutta87** [fakedrtom/SVAFotate#2]
Hi,

Thank you so much for making this tool, which has been really helpful. I have been trying to annotate my SVs from long reads meant for rare diseases using gnomad-SV Global AF values and things got really mucky when I started to take SVTYPE into account. This tool was a life saver. I have successfully annotated one of my SV VCF file that I generated using sniffles2. One small issue I faced while counting the SVs in my VCF using this command: `bcftools view -H svafolate.vcf|wc -l`, I got this error: `[W::bcf_hrec_check] Invalid tag name: "1000G_Count"
21234
`
Not sure why exactly this error came up in the annotated VCF file.

Regards,
Prasun

**Comment by fakedrtom** [comment]
Sorry for my delay, I did not receive any notification of you creating this issue! Or I otherwise missed it.

I am glad you have found the tool to be useful! 

I think I have run into this before and I suspect I may have made a mistake when beginning annotation names with "1000G_". Is this actually causing you any usability problems?

**Comment by prasundutta87** [comment]
Hi @fakedrtom, thanks for the reply. There shouldn't be any usability problems as its the VCF metadata that seems to have the issue.
